### ISSUE TITLE
Make individual channel structure for every user

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#17]

**Comment by Lebed02** [comment]
After adding a bot to the channel, for some reason he thinks that he does not have access to this channel, not sent a notification with the settings, only helps the command /show_settings

![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/c179db18-7e89-405b-a1a4-74c9f1060e40)

**Comment by Lebed02** [comment]
After an "AK 1" channel has been deleted and then re-created, the bot wants to continue sending tickets to the deleted channel, ignoring the new channel.

**Comment by Lebed02** [comment]
After creating a new channel you must first write any message in it and only then write the command "/start", from the first time the command "/start" does not work

**Comment by Lebed02** [comment]
It has been determined that this problem is related to telegram features, there is no way to fix it at this time
