### ISSUE TITLE
Create a workaroud for easier deletion of messages older than 48 hours

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#21]

**Comment by Lebed02** [comment]
![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/1b345654-5cb8-44c5-9ffc-10e7df1f752d)

After closing the ticket, the tag "#to_delete" was added to it and buttons appeared. When I clicked the "Open/Close Ticket" button, it was opened in the main channel, and the ticket was deleted from the user channel.

![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/8ebc65d4-095c-464b-a9e6-483fd0e91e80)
