### ISSUE TITLE
Reminding users about high-priority tickets

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#22]

**Comment by Lebed02** [comment]
After commenting on a ticket with the highest priority, reminders keep coming to the same user

**Comment by Lebed02** [comment]
With the same users assigned to the same account does not come a reminder of tickets

Two reminders came to the same channel for different tickets at once

**Comment by Lebed02** [comment]
When a reminder reaches a ticket that has not been forwarded to any channel, it crashes

**Comment by Lebed02** [comment]
All works good
