### ISSUE TITLE
Bug with command for adding/changing user id associated to user hashtag

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#26]

**Comment by Lebed02** [comment]
Additionally it should be added when the user is removed from the tag and assigned to the tag in the channel where the comments are sent

**Comment by Lebed02** [comment]
If you use the /set_user_tag command to add a user with "@username" and then when you click "SAVE" in the user channel, a "user not found" error appears.

**Comment by Lebed02** [comment]
All works good
