### ISSUE TITLE
Multiple bugs with CC buttons in scheduled storage channel

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#29]
Steps to reproduce:
1) Schedule ticket with followers
2) Click CC button in this ticket at scheduled channel
3) Click one of followed users buttons

Expected result:
CC buttons with followed users will contain check marks in user buttons that's following current ticket, and after pressing on button with one of ticket's followers this user will be removed from ticket's followers and removed from scheduled storage channel of this user.  

Actual result:
CC buttons missing check marks in some users, and after pressing on followed user will remove him from ticket's followers and delete ticket from scheduled channel of this user

**Comment by DnRuban** [comment]
Could not reproduce this bug, some additional conditions may be required

**Comment by Andrej-Adamenko** [comment]
Open a separate bug for each of the two problems and close this one

**Comment by DnRuban** [comment]
Scheduled ticket functionality and other parts was updated since this bug was reported, and since then this bug wasn't reproduced so it's probably fixed. Closing this issue.
