### ISSUE TITLE
Automatically remove duplicate tags

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#40]

**Comment by Lebed02** [comment]
Bug with duplicates, #п and #з not deleted

![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/e3964edc-8d77-42b3-a464-2e9d3d8c10d4)

If you postpone a message and put a user tag in front of the date, the tag is duplicated, the postponed message is broken
For example: #з 2023-08-25 16:45 #ak #п test, after trying to make it like this: #з #bb 2023-08-25 12:00 #ak #п test, the ticket will become like this: #з #bb #ak 2023-08-25 12:00 #ak #п test

**Comment by Lebed02** [comment]
After manually removing a user from a ticket and deleting the priority, the following problems occurred:

1. Errors appeared in the console.
2. When trying to press the "CC" button on a ticket, it does not close.
3. Subsequent attempts to press "CC" cause additional errors in the console.

Please consider fixing these problems for more stable system operation.

![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/aa7670f2-72fd-4ce9-8718-0ac2267891d2)

![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/ceda47cc-4556-425c-abf8-ff04c741a691)

**Comment by Lebed02** [comment]
1. If you put for example tag #т twice in the body of a ticket, the duplication will not go away, such a tag can be put in an unlimited quantity

2. The priority icon is not updated if it replaces #п with any of the priorities when both tags are in the tags

For example, if there was a tag #п and just add another tag #п1 next to it, the icon will not be updated.

**Comment by Lebed02** [comment]
Requires correction of the error described in task #39

**Comment by DnRuban** [comment]
Rebased this branch to #39, updated implementation and fixed discovered bugs to work correctly with hashtags at the last line.

**Comment by DnRuban** [comment]
Fixed the issues with reordering tags after deduplication.

**Comment by Lebed02** [comment]
A bug with spaces and duplicates was discovered

1. If you put a space at the beginning of a tag line and type a tag after it, it stays in the ticket until you press any of the keys

2. If there is one space between the tags, the duplicate is deleted, but if there are many spaces then it is not deleted. If there are many spaces and you press the button, one space is deleted, but the duplicate remains. Each click on the button removes one space, when there is only one space between the tags, then they will not be duplicated

**Comment by Lebed02** [comment]
Approved. Issues not found. All works good.
