### ISSUE TITLE
Bot shouldn't restore next action text in tickets after it was modified by user

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#45]
Additionally bot should remove any text after "::" when adding next action to ticket's body.

**Comment by Lebed02** [comment]
Enhancement:

If you create a new ticket, where you write a double colon in the text, for example, like this:
1434. #o #ak to build a barn:: buy bricks
then the bot will add the comment ": buy bricks" to the ticket immediately when creating it.

Or if I change the text after "::" by manually editing the ticket, then the bot will also add such a comment with a new next action.

But if you write a new comment starting with ":", the bot will just erase the existing text after "::".

**Comment by Lebed02** [comment]
1. After a pending ticket arrives in the channels, an error appears in the console after each pending ticket: ERROR: Exception during sending scheduled message: list.remove(x): x not in list
2. Also, the same problem with duplicate tickets is seen here as noted in task #57

**Comment by DnRuban** [comment]
Error that appears after sending scheduled tickets is related to #37 task.

**Comment by Lebed02** [comment]
Requires correction of the error described in task https://github.com/DnRuban/Taskhelper/issues/39

**Comment by DnRuban** [comment]
Rebased to branch #40, updated and fixed the bugs that was found after rebase.

**Comment by Lebed02** [comment]
Approved. Issues not found. All works good.
