### ISSUE TITLE
Add a comment after someone edited ticket's text

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#46]
Comment text: "@username edited the ticket".

**Comment by Lebed02** [comment]
After creation the ticket bot send a message that "A user edited the ticket", but user not edited the tickets, just create a new ticket

**Comment by Lebed02** [comment]
All works good

**Comment by Lebed02** [comment]
While testing another task, it was discovered that if you click the "edit" button in a newly created ticket with the very first action, and then click the "apply" checkbox with no changes, a message is displayed saying that you have changed the ticket. After the first such action on a ticket, doing it again does nothing

**Comment by DnRuban** [comment]
This is a telegram issue, for some reason after ticket was created if user clicks "Edit" button on the ticket and then presses save without modifying ticket's content telegram bot will receive notification that message was edited even though the content remained the same, and it works only the first time before anyone edited the ticket. Because telegram doesn't provide information about what was changed in the message we can't distinguish those cases from cases where ticket was really edited, so this can't be fixed.
