### ISSUE TITLE
Bug with detecting hashtags that starts with the same text as in scheduled tag

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#48]
Steps to reproduce:
1) Schedule a ticket
2) Edit this ticket and add hashtag that starts with same text as scheduled tag, for example "#зтест"
3) Wait for ticket scheduled date
4) After ticket is sent to assigned channels update it

Expected result:
Ticket is remained in the channels where it was assigned to

Actual result:
Ticket removed from channels for assigned tickets, also tag that starts with the same text as scheduled tag is moved to beginning of the ticket

Also priority tag has similar issues.

**Comment by Lebed02** [comment]
All works good
