### ISSUE TITLE
Spaces are created before the text when changing a ticket

### ISSUE THREAD

**Issue by Lebed02** [DnRuban/Taskhelper#50]
If you click on "edit" on a ticket and then click on the "apply" checkbox without changes, spaces are created before the text that the user wrote in the ticket. If you change the ticket text, spaces are also created 

Reproducible on iOS (unable to reproduce on PC and Android)

**Comment by Lebed02** [comment]
All works good

**Comment by Lebed02** [comment]
While testing another task, it was discovered that if you click the "edit" button on a ticket and then click the "apply" checkbox without making any changes, a message is displayed that you have changed the ticket. Most likely the problem is that the ticket number is expanded by 1 character and the bot corrects this so that no spaces are created and therefore the message that you have changed the ticket appears.

Reproducible on iOS (unable to reproduce on PC and Android)

**Comment by DnRuban** [comment]
Same case as in #46, because telegram doesn't provide information about what was changed in the message we can't distinguish those cases from cases where ticket was really edited, so this can't be fixed.
