### ISSUE TITLE
After deleting the ticket from main channel, ticket still locate on privat channel 

### ISSUE THREAD

**Issue by Lebed02** [DnRuban/Taskhelper#51]
If you delete a ticket from the main channel but not the pending message, the ticket remains in the private channel 

Also if you postpone a message and delete it from the main channel, the ticket will continue to be in the postponed channels, and the console will endlessly show "Error code: 400. Description: Bad Request: message to forward not found"

**Comment by Lebed02** [comment]
Rejected. Not Approved. Please fix issue:

After deleting a ticket from the main channel and trying to delete it from the personal channel by pressing the button did not lead to anything. Buttons are inactive, it gives an error in the console:INFO: Button event in unknown message 

Links to a certain ticket leads to another ticket, here is an example of such tickets:

661
https://t.me/c/1829876721/5337 

751
https://t.me/c/1829876721/5331

660
https://t.me/c/1829876721/5332

**Comment by Lebed02** [comment]
Please check if it is possible to make it so that when a deleted ticket is replaced by another existing ticket it is not found in the search under the number of the deleted ticket. Sometimes there was one content in place of the deleted ticket, but in the main canard there was a completely different content

![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/64d6a8f7-2c81-4b14-8f0e-d7d07f3fa129)

**Comment by DnRuban** [comment]
Rebased and updated this task. There is no way to fix the issue with searching deleted messages because it's handled by the telegram.

**Comment by Lebed02** [comment]
Rejected. Not Approved. Please fix issue:

When a ticket is deleted (if it was an old one and replaced by another), another ticket takes its place, when searching by the number of the deleted ticket, another ticket (which took its place) is displayed, but its buttons don't work

`INFO: Button event in unknown message [6036, -1001358772035]`

If you go to the main channel and click on CC, this ticket is re-sent to personal channels

**Comment by DnRuban** [comment]
Fixed the bug with swapping deleted ticket.

**Comment by Lebed02** [comment]
Duplicate tickets are sent, searching for them by number in the channel shows two tickets, the old ticket does not work (buttons do not function “INFO: Button event in unknown message”), the new ticket works correctly

**Comment by DnRuban** [comment]
Couldn't reproduce the bug with duplicated tickets, maybe those duplicated tickets is not related to this task, when testing please ensure that duplicated tickets is related to the tickets that was deleted from the main channel. Updated interval check to update messages from the main channel first, this should help with testing this task.

**Comment by 32felix** [comment]
Approved. Issues not found. All works good.
