### ISSUE TITLE
Problem with adding users

### ISSUE THREAD

**Issue by Lebed02** [DnRuban/Taskhelper#60]
It is necessary to make it possible to add users via username and user id

**Comment by Lebed02** [comment]
Adding users works correctly

But the same problems with duplicate tickets described in task #57 are still observed

**Comment by DnRuban** [comment]
Bot can't find a user by id if user hasn't written something to bot before, but it can always find the user by username. There is nothing we can do about this.

**Comment by DnRuban** [comment]
Updated /set_user_tag command to ensure that user has bot's chat so bot can access information about this user.

**Comment by Lebed02** [comment]
Approved. Issues not found. All works good.
