### ISSUE TITLE
Problem with default user and his priority

### ISSUE THREAD

**Issue by Lebed02** [DnRuban/Taskhelper#62]
Steps to reproduce:

1. Set a default user, such as user bb with priority 1 (using the /set_default_subchannel command)
2. When you create a ticket, the ticket is routed to specific channels according to the default values.
3. Replace user bb with user ak from the ticket body

Actual result: The ticket is removed from the channels for user bb, but is not added to the channels for user ak until it is manually prioritized.

Expected result: Ticket is removed from channels for user bb and added to channels for user ak with default priority.

**Comment by DnRuban** [comment]
Fixed in branch "feature/57".

**Comment by Lebed02** [comment]
Additional testing is required after fixing the bug that adds an open tag to a pending ticket.

**Comment by Lebed02** [comment]
For some reason, ticket 953 was forwarded to channels at 11:15, the last change for it was at 9:55 AM

[Task #62.txt](https://github.com/DnRuban/Taskhelper/files/12790680/Task.62.txt)

**Comment by Lebed02** [comment]
Approved. Issues not found. All works good

**Comment by Lebed02** [comment]
Approved. Issues not found. All works good
