### ISSUE TITLE
Bug with replacing ticket with image

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#63]
Steps to reproduce:
1) Find a ticket in one of the subchannels with an image attached that was sent there more than 48 hours ago
2) Update this ticket somehow in the main channel to trigger reforwarding

Expected result:
Oldest message in the subchannel replaces this ticket's content and updated version of this ticket sent again to this subchannel.

Actual result:
Text of the oldest ticket replaces text of this ticket, but the image remains.

**Comment by Lebed02** [comment]
Rejected. Not Approved. Please fix issue:

"Geolocation" and "gif" should be converted to tickets

**Comment by DnRuban** [comment]
Added gif message type to ticket type list, so gif messages can become tickets. Vote and geolocation messages doesn't have text, so they can't be a ticket because it's not possible to add tags to them.

**Comment by DnRuban** [comment]
Fixed the bug with deleting last message in subchannel when trying to delete ticket without text(geolocation or poll messages for example).

**Comment by Lebed02** [comment]
Approved. Issues not found. All works good.
