### ISSUE TITLE
Service tags should be in a separate line in the end of the ticket

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#66]
Additionally, the pending tag should be moved to the end.

Example:
```
123. ticket text
#о #ак #аа #з 2023-10-12
```

**Comment by DnRuban** [comment]
Looks good, can be tested.

**Comment by Lebed02** [comment]
Rejected. Not Approved. Please fix issues:

1. Right now the pending tag is displayed at the beginning, in the example at the end, the #з tag needs to be moved to the end

2. Steps to Reproduce:

a. Create a task "test" into the main channel:
111. test
#з #bb #ak #п

b. Make it pending:
111. test
#з 2024-10-10 9:00 #bb #ak #п

b. Press the button for pending messages and press “back” afterwards

Expected result: nothing's gonna change

Current result: the ticket becomes like this:
111. test
 2024-10-10 9:00 # # #
#з #bb #ak #п

Also if you make the task pending afterwards, it becomes like this:
111. test
 2024-10-10 9:00 # # #
#з 2024-10-10 9:00 #bb #ak #п

3. If you type “next action” into a newly created ticket via comments, it will be displayed like this:
321. TEST::test
#о #bb #ak #п

But if you add a new tag to the tag line, it moves to the middle and the “next action” moves to the middle:
321. TEST
 #newtag::test
#о #bb #ak #п

It should be like this:
321. TEST::test
#о #bb #ak #п #newtag

The new tag should stay in the tag line and not be moved to the middle

4. The behavior when editing a ticket should be exactly the same as if this ticket was created from scratch:
321. TEST
#о #bb #ak #п 123

This ticket should be interpreted as follows: tags are inserted in the middle of the text. So they should be duplicated in the right place, and left in the middle

321. TEST
#о #bb #ak #п 123
#о #bb #ak #п

That means: after adding “123” at the end of the tag line, the tag line is no longer considered a tag line, but a part of the text. Therefore, we need to create a new tag line and copy the tags from the middle of the text into it

**Comment by Lebed02** [comment]
Rejected. Not Approved. Please fix issues:

1. Right now the pending tag is displayed at the beginning, in the example at the end, the #з tag needs to be moved to the end

2. Steps to Reproduce:

a. Create a task "test" into the main channel:

_111. test
#з #bb #ak #п_

b. Make it pending:
_111. test
#з 2024-10-10 9:00 #bb #ak #п_

c. Press the button for pending messages and press “back” afterwards

Expected result: nothing's gonna change

Current result: the ticket becomes like this:
_111. test
 2024-10-10 9:00 # # #
#з #bb #ak #п_

Also if you make the task pending afterwards, it becomes like this (It also creates a single space at the beginning of the text in the middle of the ticket):
_111. test
  2024-10-10 9:00 # # #
#з 2024-10-10 9:00 #bb #ak #п_

3. If you type “next action” into a newly created ticket via comments, it will be displayed like this:

_321. TEST::test
#о #bb #ak #п_

But if you add a new tag to the tag line, it moves to the middle and the “next action” moves to the middle:
_321. TEST
 #newtag::test
#о #bb #ak #п_

It should be like this:
_321. TEST::test
#о #bb #ak #п #newtag_

The new tag should stay in the tag line and not be moved to the middle

4. The behavior when editing a ticket should be exactly the same as if this ticket was created from scratch:

_321. TEST
#о #bb #ak #п 123_

This ticket should be interpreted as follows: tags are inserted in the middle of the text. So they should be duplicated in the right place, and left in the middle

_321. TEST
#о #bb #ak #п 123
#о #bb #ak #п_

That means: after adding “123” at the end of the tag line, the tag line is no longer considered a tag line, but a part of the text. Therefore, we need to create a new tag line and copy the tags from the middle of the text into it

5. If you write tag #п after the existing tag #п, it will move to the middle of the ticket and after all subsequent interactions with the buttons gaps will be created between tag #п and the main text of the ticket, it looks like this (gaps between the tag and the text are the created gaps after interaction with the buttons):

_333. TEST
 gaps
 gaps
 gaps
 #п
#відкр #bb #ak #п1_

**Comment by Lebed02** [comment]
Rejected. Not Approved. Please fix issues:

1. Right now the pending tag is displayed at the beginning, in the example at the end, the #з tag needs to be moved to the end

2. Steps to Reproduce:

a. Create a task "test" into the main channel:

_111. test
#з #bb #ak #п_

b. Make it pending:
_111. test
#з 2024-10-10 9:00 #bb #ak #п_

c. Press the button for pending messages and press “back” afterwards

Expected result: nothing's gonna change

Current result: the ticket becomes like this:
_111. test
 2024-10-10 9:00 # # #
#з #bb #ak #п_

Also if you make the task pending afterwards, it becomes like this (It also creates a single space at the beginning of the text in the middle of the ticket):
_111. test
  2024-10-10 9:00 # # #
#з 2024-10-10 9:00 #bb #ak #п_

3. If you type “next action” into a newly created ticket via comments, it will be displayed like this:

_321. TEST::test
#о #bb #ak #п_

But if you add a new tag to the tag line, it moves to the middle and the “next action” moves to the middle:
_321. TEST
 #newtag::test
#о #bb #ak #п_

It should be like this:
_321. TEST::test
#о #bb #ak #п #newtag_

The new tag should stay in the tag line and not be moved to the middle

4. The behavior when editing a ticket should be exactly the same as if this ticket was created from scratch:

_321. TEST
#о #bb #ak #п 123_

This ticket should be interpreted as follows: tags are inserted in the middle of the text. So they should be duplicated in the right place, and left in the middle

_321. TEST
#о #bb #ak #п 123
#о #bb #ak #п_

That means: after adding “123” at the end of the tag line, the tag line is no longer considered a tag line, but a part of the text. Therefore, we need to create a new tag line and copy the tags from the middle of the text into it

5. If you write tag #п after the existing tag #п, it will move to the middle of the ticket and after all subsequent interactions with the buttons gaps will be created between tag #п and the main text of the ticket, it looks like this (gaps between the tag and the text are the created gaps after interaction with the buttons):

_333. TEST
 gaps
 gaps
 gaps
 #п
#о #bb #ak #п1_

**Comment by lwp-ygavrilenko** [comment]
> 1. Right now the pending tag is displayed at the beginning, in the example at the end, the #з tag needs to be moved to the end

Updated description.

**Comment by lwp-ygavrilenko** [comment]
> 2. Steps to Reproduce:
> 
> a. Create a task "test" into the main channel:
> 
> _111. test #о #bb #ak #п_
> 
> b. Make it pending: _111. test #з 2024-10-10 9:00 #bb #ak #п_
> 
> c. Press the button for pending messages and press “back” afterwards
> 
> Expected result: nothing's gonna change
> 
> Current result: the ticket becomes like this: _111. test 2024-10-10 9:00 # # # #з #bb #ak #п_
> 
> Also if you make the task pending afterwards, it becomes like this (It also creates a single space at the beginning of the text in the middle of the ticket): _111. test 2024-10-10 9:00 # # # #з 2024-10-10 9:00 #bb #ak #п_

Cannot reproduce. @Lebed02 can you try to identify the STR on a fresh install (bot, channel, chat, etc.)? If you will - please describe the steps in as much detail as possible, including installation/setup.

**Comment by DnRuban** [comment]
1. Moved scheduled tag to the end of service hashtags, currently it's not possible to use status(#o) tag with scheduled tag at the same time but it will be added in #30
2. This is the same bug as in #49, so it will be fixed there
3. Fixed
4. Fixed adding redundant space when moving tags to new line, feature with duplicating tags from the ticket's text will added in #39 so right now it won't copy tags from the middle of the text
5. Fixed the issue with adding gaps with each ticket update, feature with replacing priority tags will be added in #40

**Comment by Lebed02** [comment]
Rejected. Not Approved. Please fix issues:

1. If the ticket looked like this after manually changing the user or right after the user was created:
```
1. test::new
#о #bb #ak #п 123
```
The bot should interpret the last line not as a string of tags, but as a part of the text with tags inserted in the middle.
Namely: part of the next action.
And the bot should create the tag line anew:
```
1. test::new
#о #bb #ak #п 123
#о #bb #ak #п
```

2. There is a ticket:
```
2. test
#о #bb #ak #п #newtag
```
The tag "#newtag" is manually entered into it
If you type the text "123" at the end of the tag line, the ticket is as follows:
```
2. test
#newtag 123
#о #bb #ak #п
```
"#newtag" is moved to the middle because after adding "123", the last row is considered just part of the text, so the found tags are moved down and "#newtag" is considered part of the text and it remains

_P.S. Nothing in the middle of the text should be deleted. Tags should not be moved from the middle to the bottom, but copied down. Such as #мійтег, you don't need to copy them from the middle of the text to the last line_
