### ISSUE TITLE
Bug with reforwarding tickets that haven't been modified

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#69]
Ticket have been reforwarded to the user channel for some reason, content of the ticket remained the same. Ticket was deferred and deferred tickets couldn't be reminded so that's probably a bug.

**Comment by DnRuban** [comment]
Same bug as in #57, already fixed in #57.

**Comment by Lebed02** [comment]
Approved. Issues not found. All works good.

**Comment by DnRuban** [comment]
Issues with unchanged tickets arriving at channels was fixed in corresponding tasks. Closing the task.
