### ISSUE TITLE
Strikethrough the date in the pending tag of a ticket that has already been sent

### ISSUE THREAD

**Issue by Lebed02** [DnRuban/Taskhelper#80]
Example for a pending ticket that has reached the send date:
![image](https://github.com/user-attachments/assets/3856f1f2-01aa-4acf-859f-1b1389bd7778)

The strikethrough should also be removed if the ticket state has changed

**Comment by DnRuban** [comment]
Added strikethrough for the date in scheduled tickets depending on it's status.
