### ISSUE TITLE
Strikethrough the number of a closed ticket

### ISSUE THREAD

**Issue by Lebed02** [DnRuban/Taskhelper#81]
Example for a ticket that was closed:
![image](https://github.com/user-attachments/assets/daef0817-2b7d-4f01-9d4e-ec39e1f50576)

The strikethrough should also be removed if the ticket state has changed

**Comment by DnRuban** [comment]
Added strikethrough for the closed tickets.

**Comment by 32felix** [comment]
Approved. Issues not found. All works good.
