### ISSUE TITLE
Bug with number instead of username in bot's comment

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#83]

**Comment by DnRuban** [comment]
For some reason bot couldn't find chat by user id using bot api, seems like a telegram api issue. Added additional user retrieval method using core api if bot can't find a user using bot api, this should fix the issue.

**Comment by Lebed02** [comment]
Approved. Issues not found. All works good.

_NOTE: An issue with adding creators to CC was found and fixed_

**Comment by DnRuban** [comment]
Deployed.
