### ISSUE TITLE
Pending ticket did not arrive on time

### ISSUE THREAD

**Issue by Lebed02** [DnRuban/Taskhelper#84]
The ticket was scheduled to 11:00, it says in the console that it was sent at 11:00, but in the channels it has a send time of 10:54 (i.e. its creation time)

`2024-08-06 11:00:00,039 - {C:\test\Taskhelper\scheduled_messages_utils.py:248} INFO: Sending scheduled message [2140, -1001674661902, 1722931200]`

![image](https://github.com/user-attachments/assets/fd8a1f48-9849-4778-bebd-addf994aa424)

**Comment by DnRuban** [comment]
Couldn't reproduce the bug.
