### ISSUE TITLE
The bot keeps resending an unmodified ticket to the user channel if a phone number is present in the text

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#86]
Telegram automatically adds phone number entity to message entities if message contains numbers that look like phone number. This breaks equality checking between messages in the main channel and user channels, so every time when interval check updates the ticket bot will delete it and re-send even if it wasn't modified.

Ticket example:
902. text 0991234567 text
#о #ак #вв #п

**Comment by DnRuban** [comment]
Fixed the bug with checking equality of the messages with phone number in the text.

**Comment by 32felix** [comment]
Approved. Issues not found. All works good.
