### ISSUE TITLE
Mistakes in error description

### ISSUE THREAD

**Issue by 32felix** [DnRuban/Taskhelper#93]
Some errors for message revert description: chat not found.

Examples:
![Image](https://github.com/user-attachments/assets/9fb649cd-7101-4897-a8b5-0dcdca07d10e)
![Image](https://github.com/user-attachments/assets/1d829514-d1ab-47a3-90cc-7be0ba08b926)

**Comment by DnRuban** [comment]
"chat not found" error is returned by the Telegram API so it's not an incorrect error description. The reason why "chat not found" error appeared will be investigated further in #92 .
